In [32]:
# Importando o pandas
import pandas as pd

#Criando a função para extração dos dados necessários, ajuste das colunas e consolidação dos dados em arquivo csv
#Trocar apenas o caminho do arquivo a cada mês

def read_files(path_json, path_csv):
    empresaA = pd.read_json(path_json)
    empresaB = pd.read_csv(path_csv)
    return empresaA, empresaB

#Identificando os cabeçalhos
def unify_headers(empresaA, empresaB):
    # Adicionar a coluna 'Data da Venda' com valor 'Indisponível' se não existir
    if 'Data da Venda' not in empresaA.columns:
        empresaA['Data da Venda'] = 'Indisponível'
    
    # Verificar se os cabeçalhos são iguais
    if list(empresaA.columns) != list(empresaB.columns):
        # Renomear as colunas do DataFrame empresaB para que correspondam às do DataFrame empresaA
        empresaB.columns = empresaA.columns
    return empresaA, empresaB

def consolidar_dataframes(empresaA, empresaB): 
    # Concatenar os DataFrames verticalmente (um embaixo do outro) 
    dados_consolidados = pd.concat([empresaA, empresaB], ignore_index=True) 
    return dados_consolidados

# Caminhos dos arquivos
path_json = '../data_raw/dados_empresaA.json'
path_csv = '../data_raw/dados_empresaB.csv'

# Ler os arquivos
empresaA, empresaB = read_files(path_json, path_csv)

# Unificar cabeçalhos
empresaA, empresaB = unify_headers(empresaA, empresaB)


# Concatenar DataFrames 
dados_consolidados = consolidar_dataframes(empresaA, empresaB) 

#Verificando através da qtde de linhas se tudo foi consolidado corretamente
print('Qtde linhas esperada: ', len(empresaA) + len(empresaB))
print('Qtde linhas Consolidado:', len(dados_consolidados))

# Salvar o resultado em um novo arquivo CSV 
dados_consolidados.to_csv('../data_processed/dados_consolidados.csv', index=False, encoding='utf-8')

# Abrindo DataFrame consolidado
dados_consolidados

Qtde linhas esperada:  4446
Qtde linhas Consolidado: 4446

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial,Data da Venda
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7,Indisponível
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8,Indisponível
2,Base líquida,Roupas,75.02,34,Filial 8,Indisponível
3,Base líquida,Roupas,44.94,90,Filial 10,Indisponível
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7,Indisponível
...,...,...,...,...,...,...
4441,Lápis de sobrancelha,Alimentos,94.08,94,Filial 7,2022-11-20 18:58:06.794203
4442,Corretivo,Roupas,5.60,49,Filial 4,2023-07-16 18:58:06.794203
4443,Pó compacto,Eletrônicos,22.36,16,Filial 3,2023-01-24 18:58:06.794203
4444,Base líquida,Roupas,3.79,5,Filial 5,2022-12-18 18:58:06.794203
4445,Sombra de olhos,Eletrônicos,41.73,5,Filial 6,2022-11-21 18:58:06.794203

In [33]:
dados = pd.read_csv('../data_processed/dados_consolidados.csv')
dados

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial,Data da Venda
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7,Indisponível
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8,Indisponível
2,Base líquida,Roupas,75.02,34,Filial 8,Indisponível
3,Base líquida,Roupas,44.94,90,Filial 10,Indisponível
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7,Indisponível
...,...,...,...,...,...,...
4441,Lápis de sobrancelha,Alimentos,94.08,94,Filial 7,2022-11-20 18:58:06.794203
4442,Corretivo,Roupas,5.60,49,Filial 4,2023-07-16 18:58:06.794203
4443,Pó compacto,Eletrônicos,22.36,16,Filial 3,2023-01-24 18:58:06.794203
4444,Base líquida,Roupas,3.79,5,Filial 5,2022-12-18 18:58:06.794203
4445,Sombra de olhos,Eletrônicos,41.73,5,Filial 6,2022-11-21 18:58:06.794203