In [3]:
import pandas as pd

class DataProcessor:
    def __init__(self, path_json, path_csv):
        self.path_json = path_json
        self.path_csv = path_csv
        self.empresaA = None
        self.empresaB = None
        self.dados_consolidados = None
    
    def read_files(self):
        self.empresaA = pd.read_json(self.path_json)
        self.empresaB = pd.read_csv(self.path_csv)
    
    def unify_headers(self):
        if 'Data da Venda' not in self.empresaA.columns:
            self.empresaA['Data da Venda'] = 'Indisponível'
        
        if list(self.empresaA.columns) != list(self.empresaB.columns):
            self.empresaB.columns = self.empresaA.columns
    
    def concatenate_dataframes(self):
        self.dados_consolidados = pd.concat([self.empresaA, self.empresaB], ignore_index=True)
    
    def save_to_csv(self, output_path, sep=','):
        self.dados_consolidados.to_csv(output_path, sep=sep, index=False, encoding='utf-8')
    
    def process_data(self, output_path, sep=','):
        self.read_files()
        self.unify_headers()
        self.concatenate_dataframes()
        self.save_to_csv(output_path, sep=sep)

# Caminhos dos arquivos
path_json = '../data_raw/dados_empresaA.json'
path_csv = '../data_raw/dados_empresaB.csv'
output_path = '../data_processed/dados_consolidados.csv'

# Criar uma instância da classe e processar os dados
processor = DataProcessor(path_json, path_csv)
processor.process_data(output_path, sep=',')

# Exibir o DataFrame combinado
processor.dados_consolidados

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial,Data da Venda
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7,Indisponível
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8,Indisponível
2,Base líquida,Roupas,75.02,34,Filial 8,Indisponível
3,Base líquida,Roupas,44.94,90,Filial 10,Indisponível
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7,Indisponível
...,...,...,...,...,...,...
4441,Lápis de sobrancelha,Alimentos,94.08,94,Filial 7,2022-11-20 18:58:06.794203
4442,Corretivo,Roupas,5.60,49,Filial 4,2023-07-16 18:58:06.794203
4443,Pó compacto,Eletrônicos,22.36,16,Filial 3,2023-01-24 18:58:06.794203
4444,Base líquida,Roupas,3.79,5,Filial 5,2022-12-18 18:58:06.794203
4445,Sombra de olhos,Eletrônicos,41.73,5,Filial 6,2022-11-21 18:58:06.794203